# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 18:28
from __future__ import unicode_literals
# Generated by Django 3.0.5 on 2020-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
    ]
