# Generated by Django 3.0.6 on 2020-05-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='units',
        ),
        migrations.AddField(
            model_name='unit',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Classroom'),
        ),
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Notes'),
        ),
    ]
