# Generated by Django 3.0.5 on 2020-05-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200429_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='units',
        ),
        migrations.AddField(
            model_name='unit',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Classroom'),
        ),
    ]
