# Generated by Django 3.0.5 on 2020-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=60)),
                ('unit_code', models.CharField(max_length=60)),
                ('tutor_name', models.CharField(max_length=60)),
                ('tutor_contact', models.CharField(max_length=60)),
            ],
        ),
    ]
