# Generated by Django 3.0.6 on 2020-05-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200506_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Unit'),
        ),
    ]
