# Generated by Django 3.0.6 on 2020-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200506_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.FileField(null=True, upload_to='notes'),
        ),
    ]
