# Generated by Django 3.0.5 on 2020-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200504_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
