# Generated by Django 3.0.6 on 2020-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200606_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
