# Generated by Django 3.0.6 on 2020-06-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_notes_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='classroo_id',
            new_name='classroom_id',
        ),
    ]
