# Generated by Django 3.0.6 on 2020-06-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200606_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=60)),
                ('assignment', models.FileField(upload_to='assignments')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Unit')),
            ],
        ),
    ]
